apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ho42yvxzm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ho42yvxzm-go 
  name: ho42yvxzm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ho42yvxzm-go 
